# Generated by Django 2.1.7 on 2019-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('review', models.TextField(help_text='가차없이 적어라!!')),
                ('score', models.CharField(choices=[('A', 'Awesome'), ('B', 'Boring'), ('C', 'Choigo'), ('F', 'Fuck that')], default='Awesome', max_length=1)),
                ('book_info', models.URLField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('finished_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
