# Generated by Django 2.1.7 on 2019-03-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinglist',
            old_name='book_info',
            new_name='book_info_url',
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='duration',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='score',
            field=models.CharField(choices=[('Awesome', 'Awesome'), ('Boring', 'Boring'), ('Choigo', 'Choigo'), ('Fuck that', 'Fuck that')], default='Awesome', max_length=1),
        ),
    ]
