# Generated by Django 2.1.7 on 2019-03-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190309_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='score',
            field=models.CharField(choices=[('Awesome', 'Awesome'), ('Boring', 'Boring'), ('Choigo', 'Choigo'), ('Fuck that', 'Fuck that')], default='Awesome', max_length=15),
        ),
    ]
