# Generated by Django 2.1.7 on 2019-03-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_remove_readinglist_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('plot', models.TextField(help_text='줄거리')),
                ('published_year', models.DateField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='finished_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.ReadingList'),
        ),
    ]
