# Generated by Django 2.1.7 on 2019-03-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20190309_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='finished_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
