# Generated by Django 2.1.7 on 2019-03-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20190309_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myblog.ReadingList'),
        ),
    ]
