# Generated by Django 2.1.7 on 2019-03-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20190310_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_info_url',
        ),
    ]
