# Generated by Django 2.1.7 on 2019-03-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20190310_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_info_url',
            new_name='title',
        ),
    ]
