# Generated by Django 2.1.7 on 2019-03-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
                ('csv_file', models.FileField(upload_to='randTeam/csv_file')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
