# Generated by Django 2.1.7 on 2019-03-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randTeam', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PublishedManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
