# Generated by Django 2.1.7 on 2019-03-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randTeam', '0003_flavorreview_publishedmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
    ]
