# Generated by Django 2.1.7 on 2019-03-14 10:21

from django.db import migrations, models
import randTeam.models


class Migration(migrations.Migration):

    dependencies = [
        ('randTeam', '0004_delete_publishedmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('lottos', models.CharField(default='[1, 2, 3, 4, 5, 6]', max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('num_lotto', models.IntegerField(validators=[randTeam.models.GuessNumbers.validate_lotto])),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MyLotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lotto', models.IntegerField(validators=[randTeam.models.validate_lotto])),
            ],
        ),
    ]
