# Generated by Django 2.1.7 on 2019-03-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randTeam', '0005_guessnumbers_mylotto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guessnumbers',
            name='lottos',
            field=models.CharField(max_length=255),
        ),
    ]
