# Generated by Django 2.1.7 on 2019-03-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randTeam', '0006_auto_20190314_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('오버워치', '옵치'), ('배틀그라운', '배그'), ('하스스톤', '하스스톤'), ('히어로즈오브스톰', '히오스')], default='하스스톤', max_length=100)),
                ('content', models.TextField()),
                ('password', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='', verbose_name='이미지')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
